version: '3.8'

services:
  wa-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-gateway
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    env_file:
      - docker.env  # Optional: create this file from docker.env.example
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-5000}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:${PORT:-5000}/webhook}
      - SESSION_NAME=${SESSION_NAME:-wa-gateway-session}
      - DEBUG=${DEBUG:-false}
    volumes:
      # Persist WhatsApp session data
      - wa_session_data:/app/.wwebjs_auth
      - wa_cache_data:/app/.wwebjs_cache
      # Optional: Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - wa-gateway-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional: Add Redis for session storage (advanced usage)
  # redis:
  #   image: redis:7-alpine
  #   container_name: wa-gateway-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - wa-gateway-network
  #   command: redis-server --appendonly yes

  # Optional: Add monitoring with health check endpoint
  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: wa-gateway-watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_CLEANUP=true
  #     - WATCHTOWER_POLL_INTERVAL=3600
  #   restart: unless-stopped

volumes:
  wa_session_data:
    driver: local
  wa_cache_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  wa-gateway-network:
    driver: bridge
