version: '3.8'

services:
  wa-gateway-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: whatsapp-gateway-dev
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-5000}
      - DEBUG=${DEBUG:-true}
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:${PORT:-5000}/webhook}
      - SESSION_NAME=${SESSION_NAME:-wa-gateway-session}
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      # Persist WhatsApp session data
      - wa_session_data_dev:/app/.wwebjs_auth
      - wa_cache_data_dev:/app/.wwebjs_cache
    restart: unless-stopped
    networks:
      - wa-gateway-dev-network
    # Override command for development
    command: ["bun", "--watch", "index.ts"]
    # Remove health check for faster development
    healthcheck:
      disable: true

volumes:
  wa_session_data_dev:
    driver: local
  wa_cache_data_dev:
    driver: local

networks:
  wa-gateway-dev-network:
    driver: bridge
